BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "Charles Onesti"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "2022 Midterm Election Predictions and Analysis by Charles Onesti"
  cover = "images/user.jpg"
  author = "Charles Onesti"
  authorlocation = ""
  authorwebsite = "charlesonesti.com"
  bio= ""
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "CharlesOnesti"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
